package com.sqldalmaker.intellij.ui;

import com.intellij.openapi.ui.DialogWrapper;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import java.awt.*;
import java.awt.Desktop;

/*
 * @author sqldalmaker@gmail.com
 *
 * 30.05.2024 20:00 1.299
 * 01.09.2023 12:21 1.287
 */
public class UIDialogAbout extends DialogWrapper {

    private JPanel contentPane;
    private JButton buttonOK;
    private JTextPane textAbout;

    public static void show_modal() {
        UIDialogAbout dialog = new UIDialogAbout();
        dialog.setResizable(false);
        dialog.show();
    }

    private UIDialogAbout() {
        super(true); // modal
        setTitle("About");
        init(); // IMPORTANT: initializes DialogWrapper

        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(e -> close(OK_EXIT_CODE));

        initText();
    }

    @Override
    protected @Nullable JComponent createCenterPanel() {
        return contentPane;
    }

    @Override
    protected Action[] createActions() {
        return new Action[0]; // only close (X), OK handled manually
    }

    private void initText() {
        try {
            textAbout.setContentType("text/html");
            textAbout.setEditable(false);

            String text = IdeaHelpers.read_from_jar("", "ABOUT.html");
            String sdm_info = IdeaHelpers.get_sdm_info();
            text = String.format(text, sdm_info);
            textAbout.setText(text);

            textAbout.addHyperlinkListener(hle -> {
                if (HyperlinkEvent.EventType.ACTIVATED.equals(hle.getEventType())) {
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(hle.getURL().toURI());
                        } catch (Exception ignored) {
                        }
                    }
                }
            });
        } catch (Exception ignored) {
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        textAbout = new JTextPane();
        textAbout.setEditable(false);
        textAbout.setMargin(new Insets(0, 15, 15, 15));
        textAbout.setText("");
        panel2.add(textAbout, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(panel3, BorderLayout.SOUTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel3.add(panel4);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(buttonOK, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
