package com.sqldalmaker.intellij.ui;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.IconLoader;

import javax.swing.*;
import java.awt.*;

public class UIToolWindow {
    private JPanel panelRoot;
    private JComboBox comboBox1;
    private JButton button1;
    private JPanel panelTopbar;

    private final Project project;

    public JComponent getRootPanel() {
        return panelRoot;
    }

    public JPanel getPanelTopbar() {
        return panelTopbar;
    }

    public JButton getButton1() {
        return button1;
    }

    public JComboBox getComboBox1() {
        return comboBox1;
    }

    public UIToolWindow(Project project) {
        this.project = project;

        jbStyle(button1, "/img/_jetbrains/refresh.svg");
    }

    private static void jbStyle(JButton button, String iconRes) {
        button.setFocusable(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setOpaque(false);

        Icon icon = IconLoader.getIcon(iconRes, UIToolWindow.class);
        button.setIcon(icon);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelRoot = new JPanel();
        panelRoot.setLayout(new BorderLayout(0, 0));
        panelTopbar = new JPanel();
        panelTopbar.setLayout(new BorderLayout(0, 0));
        panelRoot.add(panelTopbar, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        panelTopbar.add(panel1, BorderLayout.WEST);
        comboBox1 = new JComboBox();
        panelTopbar.add(comboBox1, BorderLayout.CENTER);
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(36, 36));
        button1.setText("");
        button1.setToolTipText("Refresh");
        panelTopbar.add(button1, BorderLayout.EAST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new CardLayout(0, 0));
        panelRoot.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel3, "Card1");
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel4, "Card2");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelRoot;
    }

}
