//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.02 at 08:09:46 PM EET 
//


package com.sqldalmaker.jaxb.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="scope" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inheritance" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="field-names-mode" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "dto")
public class Dto {

    @XmlAttribute(name = "scope", required = true)
    protected String scope;
    @XmlAttribute(name = "inheritance", required = true)
    protected String inheritance;
    @XmlAttribute(name = "field-names-mode", required = true)
    protected int fieldNamesMode;

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the inheritance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritance() {
        return inheritance;
    }

    /**
     * Sets the value of the inheritance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritance(String value) {
        this.inheritance = value;
    }

    /**
     * Gets the value of the fieldNamesMode property.
     * 
     */
    public int getFieldNamesMode() {
        return fieldNamesMode;
    }

    /**
     * Sets the value of the fieldNamesMode property.
     * 
     */
    public void setFieldNamesMode(int value) {
        this.fieldNamesMode = value;
    }

}
