//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.31 at 10:14:10 PM EEST 
//


package com.sqldalmaker.jaxb.settings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sqldalmaker.jaxb.settings package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sqldalmaker.jaxb.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Macros }
     * 
     */
    public Macros createMacros() {
        return new Macros();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Folders }
     * 
     */
    public Folders createFolders() {
        return new Folders();
    }

    /**
     * Create an instance of {@link Dto }
     * 
     */
    public Dto createDto() {
        return new Dto();
    }

    /**
     * Create an instance of {@link Dao }
     * 
     */
    public Dao createDao() {
        return new Dao();
    }

    /**
     * Create an instance of {@link Ide }
     * 
     */
    public Ide createIde() {
        return new Ide();
    }

    /**
     * Create an instance of {@link Jdbc }
     * 
     */
    public Jdbc createJdbc() {
        return new Jdbc();
    }

    /**
     * Create an instance of {@link TypeMap }
     * 
     */
    public TypeMap createTypeMap() {
        return new TypeMap();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Macros.Macro }
     * 
     */
    public Macros.Macro createMacrosMacro() {
        return new Macros.Macro();
    }

    /**
     * Create an instance of {@link VmXml }
     * 
     */
    public VmXml createVmXml() {
        return new VmXml();
    }

    /**
     * Create an instance of {@link RootStatements }
     * 
     */
    public RootStatements createRootStatements() {
        return new RootStatements();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Elseif }
     * 
     */
    public Elseif createElseif() {
        return new Elseif();
    }

    /**
     * Create an instance of {@link Else }
     * 
     */
    public Else createElse() {
        return new Else();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Foreach }
     * 
     */
    public Foreach createForeach() {
        return new Foreach();
    }

    /**
     * Create an instance of {@link com.sqldalmaker.jaxb.settings.Macro }
     * 
     */
    public com.sqldalmaker.jaxb.settings.Macro createMacro() {
        return new com.sqldalmaker.jaxb.settings.Macro();
    }

    /**
     * Create an instance of {@link Print }
     * 
     */
    public Print createPrint() {
        return new Print();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

}
