//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.03 at 11:54:16 PM EET 
//


package com.sqldalmaker.jaxb.settings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sqldalmaker.jaxb.settings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sqldalmaker.jaxb.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Folders }
     * 
     */
    public Folders createFolders() {
        return new Folders();
    }

    /**
     * Create an instance of {@link Dto }
     * 
     */
    public Dto createDto() {
        return new Dto();
    }

    /**
     * Create an instance of {@link Dao }
     * 
     */
    public Dao createDao() {
        return new Dao();
    }

    /**
     * Create an instance of {@link ExternalVmFile }
     * 
     */
    public ExternalVmFile createExternalVmFile() {
        return new ExternalVmFile();
    }

    /**
     * Create an instance of {@link Ide }
     * 
     */
    public Ide createIde() {
        return new Ide();
    }

    /**
     * Create an instance of {@link Cpp }
     * 
     */
    public Cpp createCpp() {
        return new Cpp();
    }

    /**
     * Create an instance of {@link Jdbc }
     * 
     */
    public Jdbc createJdbc() {
        return new Jdbc();
    }

    /**
     * Create an instance of {@link TypeMap }
     * 
     */
    public TypeMap createTypeMap() {
        return new TypeMap();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

}
