//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.28 at 02:15:53 PM EEST 
//


package com.sqldalmaker.jaxb.settings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for root-statements complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="root-statements"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence maxOccurs="unbounded" minOccurs="0"&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element ref="{}if"/&amp;gt;
 *           &amp;lt;element ref="{}set"/&amp;gt;
 *           &amp;lt;element ref="{}foreach"/&amp;gt;
 *           &amp;lt;element ref="{}macro"/&amp;gt;
 *           &amp;lt;element ref="{}print"/&amp;gt;
 *           &amp;lt;element ref="{}br"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "root-statements", propOrder = {
    "ifOrSetOrForeach"
})
@XmlSeeAlso({
    VmXml.class,
    Macro.class,
    Foreach.class,
    Else.class,
    Elseif.class,
    If.class
})
public class RootStatements {

    @XmlElements({
        @XmlElement(name = "if", type = If.class),
        @XmlElement(name = "set", type = Set.class),
        @XmlElement(name = "foreach", type = Foreach.class),
        @XmlElement(name = "macro", type = Macro.class),
        @XmlElement(name = "print", type = Print.class),
        @XmlElement(name = "br", type = Br.class)
    })
    protected List<Object> ifOrSetOrForeach;

    /**
     * Gets the value of the ifOrSetOrForeach property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the ifOrSetOrForeach property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIfOrSetOrForeach().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link If }
     * {@link Set }
     * {@link Foreach }
     * {@link Macro }
     * {@link Print }
     * {@link Br }
     * 
     * 
     */
    public List<Object> getIfOrSetOrForeach() {
        if (ifOrSetOrForeach == null) {
            ifOrSetOrForeach = new ArrayList<Object>();
        }
        return this.ifOrSetOrForeach;
    }

}
