//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.03 at 11:54:16 PM EET 
//


package com.sqldalmaker.jaxb.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}folders"/>
 *         &lt;element ref="{}dto"/>
 *         &lt;element ref="{}dao"/>
 *         &lt;element ref="{}external-vm-file"/>
 *         &lt;element ref="{}ide"/>
 *         &lt;element ref="{}cpp"/>
 *         &lt;element ref="{}jdbc"/>
 *         &lt;element ref="{}type-map" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "folders",
    "dto",
    "dao",
    "externalVmFile",
    "ide",
    "cpp",
    "jdbc",
    "typeMap"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    protected Folders folders;
    @XmlElement(required = true)
    protected Dto dto;
    @XmlElement(required = true)
    protected Dao dao;
    @XmlElement(name = "external-vm-file", required = true)
    protected ExternalVmFile externalVmFile;
    @XmlElement(required = true)
    protected Ide ide;
    @XmlElement(required = true)
    protected Cpp cpp;
    @XmlElement(required = true)
    protected Jdbc jdbc;
    @XmlElement(name = "type-map")
    protected TypeMap typeMap;

    /**
     * Gets the value of the folders property.
     * 
     * @return
     *     possible object is
     *     {@link Folders }
     *     
     */
    public Folders getFolders() {
        return folders;
    }

    /**
     * Sets the value of the folders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Folders }
     *     
     */
    public void setFolders(Folders value) {
        this.folders = value;
    }

    /**
     * Gets the value of the dto property.
     * 
     * @return
     *     possible object is
     *     {@link Dto }
     *     
     */
    public Dto getDto() {
        return dto;
    }

    /**
     * Sets the value of the dto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dto }
     *     
     */
    public void setDto(Dto value) {
        this.dto = value;
    }

    /**
     * Gets the value of the dao property.
     * 
     * @return
     *     possible object is
     *     {@link Dao }
     *     
     */
    public Dao getDao() {
        return dao;
    }

    /**
     * Sets the value of the dao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dao }
     *     
     */
    public void setDao(Dao value) {
        this.dao = value;
    }

    /**
     * Gets the value of the externalVmFile property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalVmFile }
     *     
     */
    public ExternalVmFile getExternalVmFile() {
        return externalVmFile;
    }

    /**
     * Sets the value of the externalVmFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalVmFile }
     *     
     */
    public void setExternalVmFile(ExternalVmFile value) {
        this.externalVmFile = value;
    }

    /**
     * Gets the value of the ide property.
     * 
     * @return
     *     possible object is
     *     {@link Ide }
     *     
     */
    public Ide getIde() {
        return ide;
    }

    /**
     * Sets the value of the ide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ide }
     *     
     */
    public void setIde(Ide value) {
        this.ide = value;
    }

    /**
     * Gets the value of the cpp property.
     * 
     * @return
     *     possible object is
     *     {@link Cpp }
     *     
     */
    public Cpp getCpp() {
        return cpp;
    }

    /**
     * Sets the value of the cpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpp }
     *     
     */
    public void setCpp(Cpp value) {
        this.cpp = value;
    }

    /**
     * Gets the value of the jdbc property.
     * 
     * @return
     *     possible object is
     *     {@link Jdbc }
     *     
     */
    public Jdbc getJdbc() {
        return jdbc;
    }

    /**
     * Sets the value of the jdbc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jdbc }
     *     
     */
    public void setJdbc(Jdbc value) {
        this.jdbc = value;
    }

    /**
     * Gets the value of the typeMap property.
     * 
     * @return
     *     possible object is
     *     {@link TypeMap }
     *     
     */
    public TypeMap getTypeMap() {
        return typeMap;
    }

    /**
     * Sets the value of the typeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeMap }
     *     
     */
    public void setTypeMap(TypeMap value) {
        this.typeMap = value;
    }

}
