//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.18 at 11:12:54 AM EEST 
//


package com.sqldalmaker.jaxb.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{}folders"/&amp;gt;
 *         &amp;lt;element ref="{}dto"/&amp;gt;
 *         &amp;lt;element ref="{}dao"/&amp;gt;
 *         &amp;lt;element ref="{}ide"/&amp;gt;
 *         &amp;lt;element ref="{}cpp"/&amp;gt;
 *         &amp;lt;element ref="{}jdbc"/&amp;gt;
 *         &amp;lt;element ref="{}type-map"/&amp;gt;
 *         &amp;lt;element ref="{}macros"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "folders",
    "dto",
    "dao",
    "ide",
    "cpp",
    "jdbc",
    "typeMap",
    "macros"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    protected Folders folders;
    @XmlElement(required = true)
    protected Dto dto;
    @XmlElement(required = true)
    protected Dao dao;
    @XmlElement(required = true)
    protected Ide ide;
    @XmlElement(required = true)
    protected Cpp cpp;
    @XmlElement(required = true)
    protected Jdbc jdbc;
    @XmlElement(name = "type-map", required = true)
    protected TypeMap typeMap;
    @XmlElement(required = true)
    protected Macros macros;

    /**
     * Gets the value of the folders property.
     * 
     * @return
     *     possible object is
     *     {@link Folders }
     *     
     */
    public Folders getFolders() {
        return folders;
    }

    /**
     * Sets the value of the folders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Folders }
     *     
     */
    public void setFolders(Folders value) {
        this.folders = value;
    }

    /**
     * Gets the value of the dto property.
     * 
     * @return
     *     possible object is
     *     {@link Dto }
     *     
     */
    public Dto getDto() {
        return dto;
    }

    /**
     * Sets the value of the dto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dto }
     *     
     */
    public void setDto(Dto value) {
        this.dto = value;
    }

    /**
     * Gets the value of the dao property.
     * 
     * @return
     *     possible object is
     *     {@link Dao }
     *     
     */
    public Dao getDao() {
        return dao;
    }

    /**
     * Sets the value of the dao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dao }
     *     
     */
    public void setDao(Dao value) {
        this.dao = value;
    }

    /**
     * Gets the value of the ide property.
     * 
     * @return
     *     possible object is
     *     {@link Ide }
     *     
     */
    public Ide getIde() {
        return ide;
    }

    /**
     * Sets the value of the ide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ide }
     *     
     */
    public void setIde(Ide value) {
        this.ide = value;
    }

    /**
     * Gets the value of the cpp property.
     * 
     * @return
     *     possible object is
     *     {@link Cpp }
     *     
     */
    public Cpp getCpp() {
        return cpp;
    }

    /**
     * Sets the value of the cpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpp }
     *     
     */
    public void setCpp(Cpp value) {
        this.cpp = value;
    }

    /**
     * Gets the value of the jdbc property.
     * 
     * @return
     *     possible object is
     *     {@link Jdbc }
     *     
     */
    public Jdbc getJdbc() {
        return jdbc;
    }

    /**
     * Sets the value of the jdbc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jdbc }
     *     
     */
    public void setJdbc(Jdbc value) {
        this.jdbc = value;
    }

    /**
     * Gets the value of the typeMap property.
     * 
     * @return
     *     possible object is
     *     {@link TypeMap }
     *     
     */
    public TypeMap getTypeMap() {
        return typeMap;
    }

    /**
     * Sets the value of the typeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeMap }
     *     
     */
    public void setTypeMap(TypeMap value) {
        this.typeMap = value;
    }

    /**
     * Gets the value of the macros property.
     * 
     * @return
     *     possible object is
     *     {@link Macros }
     *     
     */
    public Macros getMacros() {
        return macros;
    }

    /**
     * Sets the value of the macros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Macros }
     *     
     */
    public void setMacros(Macros value) {
        this.macros = value;
    }

}
