//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 12:08:24 PM EET 
//


package com.sqldalmaker.jaxb.dao;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sqldalmaker.jaxb.dao package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sqldalmaker.jaxb.dao
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Crud }
     * 
     */
    public Crud createCrud() {
        return new Crud();
    }

    /**
     * Create an instance of {@link TypeCrud }
     * 
     */
    public TypeCrud createTypeCrud() {
        return new TypeCrud();
    }

    /**
     * Create an instance of {@link TypeMethod }
     * 
     */
    public TypeMethod createTypeMethod() {
        return new TypeMethod();
    }

    /**
     * Create an instance of {@link QueryDto }
     * 
     */
    public QueryDto createQueryDto() {
        return new QueryDto();
    }

    /**
     * Create an instance of {@link ExecDml }
     * 
     */
    public ExecDml createExecDml() {
        return new ExecDml();
    }

    /**
     * Create an instance of {@link QueryDtoList }
     * 
     */
    public QueryDtoList createQueryDtoList() {
        return new QueryDtoList();
    }

    /**
     * Create an instance of {@link QueryList }
     * 
     */
    public QueryList createQueryList() {
        return new QueryList();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link CrudAuto }
     * 
     */
    public CrudAuto createCrudAuto() {
        return new CrudAuto();
    }

    /**
     * Create an instance of {@link DaoClass }
     * 
     */
    public DaoClass createDaoClass() {
        return new DaoClass();
    }

}
